apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: infrastructure
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "adminpassword"
  # Cookie necesaria para clustering; la dejamos fija para estabilidad (aunque uses 1 réplica).
  RABBITMQ_ERLANG_COOKIE: "supersecretcookiechangeme"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: infrastructure
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  # Usa el StorageClass por defecto de tu cluster.
  # Si necesitas uno específico, descomenta la línea de abajo y cámbialo:
  # storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: infrastructure
  labels: { app: rabbitmq }
spec:
  replicas: 1
  selector:
    matchLabels: { app: rabbitmq }
  template:
    metadata:
      labels: { app: rabbitmq }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          # Probes recomendadas por RabbitMQ
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics","-q","ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics","-q","ping"]
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-data
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: infrastructure
  labels: { app: rabbitmq }
spec:
  type: ClusterIP
  selector: { app: rabbitmq }
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
---
# (Opcional) Servicio para la consola web de RabbitMQ
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mgmt
  namespace: infrastructure
  labels: { app: rabbitmq }
spec:
  type: ClusterIP
  selector: { app: rabbitmq }
  ports:
    - name: http
      port: 15672
      targetPort: 15672
