apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - ../../base
  - externalsecrets.yaml
  - hpa.yaml
  - ingress.yaml
  - servicemonitor.yaml
images:
  - name: REPOSITORY/auth-service
    newName: kristianrpo30/auth-microservice
    newTag: latest