apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-local-data
  namespace: documents
  labels: { app: dynamodb-local }
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Si tu cluster tiene un storageClass específico (ej. "standard", "local-path"), descomenta la siguiente línea:
  # storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local
  namespace: documents
  labels: { app: dynamodb-local }
spec:
  replicas: 1
  selector:
    matchLabels: { app: dynamodb-local }
  template:
    metadata:
      labels: { app: dynamodb-local }
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local:latest
          # Quitamos -inMemory y agregamos -dbPath apuntando al volumen persistente
          args: ["-jar", "DynamoDBLocal.jar", "-dbPath", "/home/dynamodblocal/data", "-sharedDb"]
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: dynamodb-data
              mountPath: /home/dynamodblocal/data
      volumes:
        - name: dynamodb-data
          persistentVolumeClaim:
            claimName: dynamodb-local-data
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  namespace: documents
  labels: { app: dynamodb-local }
spec:
  type: ClusterIP
  selector: { app: dynamodb-local }
  ports:
    - name: dynamodb
      port: 8000
      targetPort: 8000
---
# Job para crear (o recrear) la tabla Documents
apiVersion: batch/v1
kind: Job
metadata:
  name: dynamodb-create-table
  namespace: documents
spec:
  backoffLimit: 3
  # (Opcional) Limpia automáticamente el Job después de 60s de terminar
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "admin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "admin123"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
          command: ["sh", "-c"]
          args:
            - |
              set -e

              ENDPOINT="http://dynamodb-local.documents.svc.cluster.local:8000"

              echo "Esperando a que DynamoDB Local esté disponible en ${ENDPOINT}..."
              # Espera activa hasta que responda
              for i in $(seq 1 30); do
                if aws dynamodb list-tables --endpoint-url "${ENDPOINT}" --region us-east-1 >/dev/null 2>&1; then
                  echo "DynamoDB Local listo."
                  break
                fi
                echo "Aún no responde, reintentando..."
                sleep 2
              done

              echo "Creando tabla Documents (si no existe)..."
              aws dynamodb create-table \
                --table-name Documents \
                --attribute-definitions \
                  AttributeName=DocumentID,AttributeType=S \
                  AttributeName=OwnerID,AttributeType=N \
                  AttributeName=HashSHA256,AttributeType=S \
                --key-schema \
                  AttributeName=DocumentID,KeyType=HASH \
                  AttributeName=OwnerID,KeyType=RANGE \
                --provisioned-throughput \
                  ReadCapacityUnits=5,WriteCapacityUnits=5 \
                --global-secondary-indexes \
                  '[
                    {
                      "IndexName": "OwnerIDIndex",
                      "KeySchema": [
                        {"AttributeName": "OwnerID", "KeyType": "HASH"}
                      ],
                      "Projection": {"ProjectionType": "ALL"},
                      "ProvisionedThroughput": {
                        "ReadCapacityUnits": 5,
                        "WriteCapacityUnits": 5
                      }
                    },
                    {
                      "IndexName": "HashOwnerIndex",
                      "KeySchema": [
                        {"AttributeName": "HashSHA256", "KeyType": "HASH"},
                        {"AttributeName": "OwnerID", "KeyType": "RANGE"}
                      ],
                      "Projection": {"ProjectionType": "ALL"},
                      "ProvisionedThroughput": {
                        "ReadCapacityUnits": 5,
                        "WriteCapacityUnits": 5
                      }
                    }
                  ]' \
                --endpoint-url "${ENDPOINT}" \
                --region us-east-1 || echo "Tabla ya existe"

              echo "✓ Tabla Documents OK"
              echo "  - Key: DocumentID (HASH) + OwnerID (RANGE)"
              echo "  - GSI: OwnerIDIndex (OwnerID)"
              echo "  - GSI: HashOwnerIndex (HashSHA256 + OwnerID)"
