apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: documents-ingress
  namespace: documents
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: documents-service
                port:
                  number: 80
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: documents-service
                port:
                  number: 80
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: documents-service
                port:
                  number: 80
